.\" Copyright (c) 2018 brickviking (brickviking@gmail.com),
.\"     Fri Apr  6 10:54:00 NZST 2018
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, download it from the www.fsf.org
.\" website or write to the Free Software Foundation, Inc., 59 Temple Place,
.\" Suite 330, Boston, MA 02111, USA.
.\"
.\" Version 0.1.1 for minecrafty 0.58.
.\" TODO: fix up the Launcher Options section the same as the Fetch Options section
.\" 
.TH MINECRAFTY 6 2018-10-23 "Linux" "Java games"
.SH NAME
minecrafty \- A Minecraft launcher front end.
.SH SYNOPSIS
.B minecrafty " " [-hvGTSBEOP] 
.BI "[-b " "n.n"]
.BI "[-g " "n.n"]
.B [-m " " 0|1|2]
.BI "[-r " "nn.n"]
.BI "[-z " "XxY" "] ..."
.TP
.BI minecrafty " " "[-f " launcher_name "] ..."
.TP
.BI minecrafty " " "[-l " launcher_name "] ..."
.TP
.BI minecrafty " " "[-s" " servername" "] ..."
.SH DESCRIPTION
.B minecrafty
executes a java launcher for the computer game Minecraft.
When
.B minecrafty
is started with no arguments, it runs the Minecraft launcher found in
.I "${HOME}/.minecraft/bin/minecraft_launcher.jar"
if you have already downloaded and installed it in the above location.
Optionally, you can download or start Minecraft launchers or download
java versions of vanilla Minecraft.
.SH OPTIONS
.SS General options
Options for minecrafty are as follows:
.TP
.B -h
prints the main help screen for 
.BR minecrafty .
Further help details are described under the
.B Launcher options
and
.B Fetching options
sections.
.TP
.B -v
show minecrafty's version string
.TP
.B -G
sets the output file to
.I ${HOME}/.minecraft/minecrafty.output.txt
.SS Memory options
These options affect how much memory the launcher will start with. This does
.I not
affect how much memory that Minecraft itself will start with, just the amount
assigned to the launcher. Historically (previous to 1.5.2) the amount assigned
on the commandline affected how much memory the Minecraft game started with.
.TP
.B -T
runs launcher with a tiny amount of memory (256 mb).
.TP
.B -S
runs launcher with a normal amount of memory (512 Mb).
This is the default if no memory option is chosen.
.TP
.B -B
runs launcher with a larger amount of memory (1024 mb).
.TP
.B -E
runs launcher with heaps of memory, only on 64-bit systems (2 Gb).
.SS Audio options
These are needed if you need pulseaudio to be tweaked or simply get out of the way.
.TP
.B -O
create OSS-like pulseaudio device.
.TP
.B -P
suspends pulseaudio while minecraft runs.
.SS Graphical options
These affect what you see on your screen.
.TP
.BI -b " n.n"
set the brightness to the value specified as 
.I n.n,
for example 
.B -b 1.0.
If unset, 1.0 is used. 0.7 darker, 1.2 lighter.
.TP
.BI -g " n.n"
set the gamma offset. If unset, 1.0 is used. 0.7 lighter, 1.2 darker.
.TP
.B -m <0|1|2|3>
select monitor to apply gamma correction to
.TP
.BI -r nn.n
set a valid refresh rate for the second monitor, as minecraft has a habit
of setting this to the recommended value (often 60 Hz) instead of the
value used when your screen started. This applies to people who have
specifically set 75 Hz or some other refresh rate.
.TP 
.BI -z XxY
set required resolution (1920x1080 default).
.SS Fetching options
.TP
.B -f help
produces help for fetching launchers and minecraft versions.
.TP
.BI "-f <" "n.n" " |" n.n.n ">"
retrieves a release version of 
.I minecraft.jar,
examples of this are
.B 1.0
or
.BR 1.10.2 .
This script doesn't fetch versions earlier than 1.0, but the default launcher
will now fetch earlier versions such as alpha and beta.
.TP
.B -f <YEARwWEEKx>
retrieves a snapshot version of minecraft.jar, such as 17w49b.
.B Year
starts from 11, and (so far) goes to 18 but will eventually range up to
29. 
.B WEEK
ranges from 01 to 53,
.B x
is a letter from a to m. The earliest snapshot version that exists in this format is 11w47a;
although there were earlier snapshot versions, they don't folllow this
naming convention.
.TP
.BI -f " launcher_name"
retrieves
.I launcher_name
from the relevant remote host such as the FTB launcher.
The valid choices are:
.RS
.B launcher
.br
.B default
.br
.B vanilla
downloads the default launcher.
.TP
.B craft
download Craftland installer for latest Aether prerelease.
.TP
.B digiex
download DigiEX launcher (obsolete, may not work).
.TP
.B ftb
download FTB launcher
.TP
.B magic
download MagicLauncher
.\" .TP
.\" .B multi
.\" download MultiMC (commented out until I find a new host for MultiMC)
.TP
.B skmc
download development version of SKMCLauncher.jar (obsolete, may not work).
.TP
.B technic
download beta Technic launcher.
.TP
.B terra
download beta TerraFirmaCraft launcher (1.5.1 only).
.TP
.B mvc
download Minecraft Version Changer from TunkDesign. (probably obsolete)
.\" .TP
.\" .B bukkitrb
.\" download latest recommended bukkit build (obsolete due to a DMCA claim)
.TP
.B atl
download AT Launcher for Linux.
.TP
.B aether
download Aether Launcher. This seems to be the latest Aether II project.
Currently it doesn't work, and development versions of 1.10.2 and 1.11.2
are using a profile created on the default launcher.
.RE
.SS Launcher options
.TP
.B -l help
produces help for starting minecraft launchers.
.TP
.BI -l " launcher_name"
starts specified launcher. So does simply typing
.B minecrafty
at the prompt. The valid choices are:
.RS
.B default
.br
.B launcher
.br
.B vanilla
run default launcher
.TP
.B craft
run CraftLand launcher
.TP
.B digiex
run DigiEX launcher
.TP
.B magic
run MagicLauncher
.TP
.B multi
run MultiMC
.TP
.B skmc
run development version of SKMCLauncher.jar
.TP
.B ftb
run FTB launcher
.TP
.B technic
run Technic launcher
.TP
.B terra
run beta TerraFirmaCraft launcher (1.5.1 only)
.TP
.B mvc
run Minecraft Version Changer (MVC.jar)
.TP
.B atl
run AT Launcher
.TP
.B aether
run Aether Launcher
.RE
.SS Starting a server
.TP
.BI -s " server_name"
starts the latest server from 
.I "${HOME}/.minecraft/server",
supply a correct filename.

.SH EXAMPLES
.TP
.B minecrafty
executes the default launcher with default amount of memory assigned to it.
.TP
.B minecrafty -l ftb
executes the FTB launcher with default amount of memory assigned to it.
.TP
.B minecrafty -f 1.12.2
fetch the jar file for the 1.12.2 client, saving it in the correct place.
.TP
.B minecrafty -m 1 -g 1.3 -z 1360x768 -r 75 -G
execute the default launcher, setting the screensize, refresh rate and gamma
for the second monitor. Console output will be in
.I ${HOME}/.minecraft/minecrafty.output.txt
for you to look at if you have problems later.

.SH BUGS
No doubt there are some, I still haven't winkled out all the bugs in the
graphics options yet, and most of the launchers aren't around any more.
The return value from minecrafty will be different if you use the logfile
option
.B -G
as the exit value will actually be from the program used to capture the output.
Thankfully, I can recommend the FTB launcher, which is kept up to date.

.SH AUTHORS
Me, of course (brickviking@gmail.com). I've had a little bit of help from others too.

.SH ############ End of page

